@baseUrl = https://localhost:5001

// ======================================================================================
// Stock aggregate request ===============================================================

### GetInventoryStock
GET {{baseUrl}}/api/tenants/1bb91b7f-f6f4-5ec4-eef8-157e1fbb700f/inventory/stocks/04e51808-b086-dfe3-8772-cfe35f0f65e1 HTTP/1.1

### GetInventoryStocks
GET {{baseUrl}}/api/tenants/1bb91b7f-f6f4-5ec4-eef8-157e1fbb700f/inventory/stocks/ HTTP/1.1

### CreateInventoryStockMovement
POST {{baseUrl}}/api/tenants/1bb91b7f-f6f4-5ec4-eef8-157e1fbb700f/inventory/stocks/04e51808-b086-dfe3-8772-cfe35f0f65e1/movements
Content-Type: application/json

{
  "quantity": 1,
  "type": 0,
  "reason": "added",
  "timestamp": "2024-10-07T22:25:57.979Z"
}