services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: bdk_bookfiesta_mssql
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Abcd1234!
      - MSSQL_PID=Developer
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S mssql -U SA -P 'Abcd1234!' -Q 'select 1'
    ports:
      - 14340:1433
    volumes:
      - mssql:/var/opt/mssql
    networks:
      - bdk_bookfiesta

  mssqlscripts:
    image: mcr.microsoft.com/mssql-tools:latest
    container_name: bdk_bookfiesta_mssqlscripts
    depends_on:
      - mssql
    command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "Abcd1234!" -Q "SELECT @@VERSION"; do sleep 5; done'
    networks:
      - bdk_bookfiesta

  seq:
    image: datalust/seq:preview
    container_name: bdk_bookfiesta_seq
    restart: unless-stopped
    ports:
      - 15340:80 # http://localhost:15340 azure:https://ml-software.ch/posts/running-seq-on-azure
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=admin
      # https://blog.datalust.co/setting-an-initial-password-when-deploying-seq-to-docker/
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=FIQIay86/lqTJOWoq8jeh1KUr3wSfubJJ+/mB+fluLSK+ZhBQQ==
    volumes:
      - seq:/data
    networks:
      - bdk_bookfiesta

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: bdk_bookfiesta_jaeger
    restart: unless-stopped
    ports:
      - 5778:5775/udp
      - 5779:5778
      - 6838:6831/udp
      - 6839:6832/udp # AgentPort
      - 9419:9411
      - 14269:14268
      - 16689:16686 # http://localhost:16689
    environment:
      # https://www.jaegertracing.io/docs/1.16/deployment/#badger---local-storage
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
    volumes:
      - jaeger:/badger
    networks:
      - bdk_bookfiesta

volumes:
  mssql:
    name: bdk_bookfiesta_mssql
    driver: local
  seq:
    name: bdk_bookfiesta_seq
    driver: local
  jaeger:
    name: bdk_bookfiesta_jaeger
    driver: local

networks:
  bdk_bookfiesta:
    name: bdk_bookfiesta
    driver: bridge