@baseUrl = https://localhost:5001

// ======================================================================================
// Company aggregate request ============================================================

### GetOrganizationCompany
GET {{baseUrl}}/api/organization/companies/17f27051-9de9-04f0-65ca-08ec139e9953 HTTP/1.1

### GetOrganizationCompanyTenants
GET {{baseUrl}}/api/organization/companies/17f27051-9de9-04f0-65ca-08ec139e9953/tenants HTTP/1.1

### GetOrganizationCompanies
GET {{baseUrl}}/api/organization/companies/ HTTP/1.1

// ======================================================================================
// Tenant aggregate request ============================================================

### GetOrganizationTenant
GET {{baseUrl}}/api/organization/tenants/1bb91b7f-f6f4-5ec4-eef8-157e1fbb700f HTTP/1.1

### GetOrganizationTenants
GET {{baseUrl}}/api/organization/tenants/ HTTP/1.1